name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish to pub.dev
        uses: afonsocraposo/actions-flutter-pub-publisher@v1.1.0
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          skip_test: true

